services:
  redis:
    image: redis/redis-stack-server:7.2.0-v18
    container_name: redis
    restart: always
    env_file:
      - .env
    ports:
      - "6378:6378"
      - "8211:8211"
    volumes:
      - redis_stack_data:/data
    networks:
      - app_network

  bot-service:
    build:
      context: ./bot-service
      dockerfile: Dockerfile
    container_name: tg_service
    restart: always
    ports:
      - "8019:8019"
    env_file:
      - .env
    networks:
      - app_network


volumes:
  redis_stack_data:
  portainer_data:

networks:
  app_network:
    driver: bridge